spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址，注意前面不要加协议http
        server-addr: 192.168.221.128:8848
        # 指定namespace
        # namespace: c8feaebd-fac2-4c27-8b46-ca7709b9c62c
        # 指定集群名称
        # cluster-name: NJ
        metadata:
          version: 1.0
          hello: world
  application:
    # 服务名称尽量用中-，不要用_，更不要用特殊字符串
    name: user-center
server:
  port: 8080
