spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址，注意前面不要加协议http
        server-addr: 192.168.221.128:8848
  application:
    # 服务名称尽量用中-，不要用_，更不要用特殊字符串
    name: content-center
  # 允许bean define 覆盖
  main:
    allow-bean-definition-overriding: true
server:
  port: 8010

user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# ribbon 饥饿加载
ribbon:
  eager-load:
    enabled: true
    # 这里可以细粒度配置哪些微服务需要饥饿加载，多个用逗号分隔
    clients: user-center
logging:
  level:
    com.yicj.contentcenter.feignclient.UserCenterFeignClient: debug
#feign.client.config.<feignName>.loggerLevel=full   # 通常feignName即微服务的名称
feign:
  client:
    config:
      # 微服务的名称
      user-center:
        loggerLevel: full

