# 表示访问gateway的/** 才会转发到user-center/**
spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://user-center
          predicates:
            # 当且仅当请求时的时间After配置的时间时，才会转发到用户微服务
            # 目前配置不会进该路由配置，所以返回404
            # 将时间改成 < now的时间，则访问localhost:8040/** -> user-center/**
            # eg. 访问http://localhost:8040/users/1 -> user-center/users/1
            - Path=/users/**
            - After=2010-01-20T17:42:47.789-07:00[America/Denver]
            - TimeBetween=上午0:00,下午11:59
          filters:
            - AddRequestParameter=foo, bar
            - PreLog=a,b
        - id: ontent_route
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/**